# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a6ad6b4151e8cd0d68dbaf51195f584882a25c145973b616abb3538512504fb90eb77693f89f15fcd5df8fad81f1acdede3f7c9b0ba5452af383e616164ad7

test:
  secret_key_base: 305a2fddfb64024b354233947178b15eb98d30fc2636a47152b8b111d94a505d863bd8726fc1cd577ab8356813e14baa7250cc6c3ef68484a01c4ce0f5d3df6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
